name: Lint

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v4

      # https://github.com/rhysd/actionlint
      - name: run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - name: checkout
      uses: actions/checkout@v4

    # https://github.com/actions/setup-python
    - name: sest up python
      uses: actions/setup-python@v4

    # https://github.com/pre-commit/action
    - name: run pre-commit
      uses: pre-commit/action@v3.0.1
      env:
        SKIP: no-commit-to-branch
